// title
export const TITLE_SET = 'TITLE_SET';
export const TITLE_FETCH = 'TITLE_FETCH';
export const CONNECTIVITY_SET = 'CONNECTIVITY_SET';
export const NAME_SET = 'NAME_SET';
export const SET_VIEW_COORDS = 'SET_VIEW_COORDS';
export const SET_MARKERS = 'SET_MARKERS';
export const ADD_MARKER = 'ADD_MARKER';
export const FETCH_TREE_LIST = 'FETCH_TREE_LIST';
export const SET_TREE_LIST = 'SET_TREE_LIST';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const SET_USER_DATA = 'SET_USER_DATA';
export const ADD_TO_TREE_LIST = 'ADD_TO_TREE_LIST';
export const ADD_TREE = 'ADD_TREE';
export const LOGIN_ANONYMOUSLY = 'LOGIN_ANONYMOUSLY';
export const LOGIN_WITH_EMAIL = 'LOGIN_WITH_EMAIL';
export const SIGNUP_WITH_EMAIL = 'SIGNUP_WITH_EMAIL';
export const SET_ADD_MARKER = 'SET_ADD_MARKER';
export const SHOW_ADD_MARKER = 'SHOW_ADD_MARKER';
export const HIDE_ADD_MARKER = 'HIDE_ADD_MARKER';
export const SET_ADD_TREE_MODAL = 'SET_ADD_TREE_MODAL';
export const SHOW_ADD_TREE_MODAL = 'SHOW_ADD_TREE_MODAL';
export const HIDE_ADD_TREE_MODAL = 'HIDE_ADD_TREE_MODAL';
export const LOGOUT_WITH_GOOGLE = 'LOGOUT_WITH_GOOGLE';
export const LOGOUT_ANONYMOUSLY = 'LOGOUT_ANONYMOUSLY';
export const LOGOUT_WITH_EMAIL = 'LOGOUT_WITH_EMAIL';

// errors
export const GENERIC_ERROR = 'GENERIC_ERROR';
